server:
  port:  9089

spring:
  datasource:
    jdbc-url: "jdbc:mysql://localhost:33306/szkolenie?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: "root"
    password: "hard_password"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"